✨style: improve visibility of invalid port number warning message
euotiniel/og-local pull request #6
Opened 2024-08-05 20:41 UTC by noejunior792

2024-08-05 21:44 UTC, euotiniel requested changes
Submit a screenshot with this change, please.

2024-08-05 21:44 UTC, euotiniel commented on src/App.vue
> +        return { color: "black" };
Black? Do you can to send a picture?

2024-08-06 19:39 UTC, noejunior792 commented on src/App.vue
> +        return { color: "black" };
![Captura de ecrã 2024-08-06 074322](https://github.com/user-attachments/assets/3be50c51-9b8f-43e5-a048-acfd0081894b)
Well, I'm not a good designer, but I understand how it works and for me a good design has to be functional, that's why I chose the color black.

2024-08-08 15:19 UTC, euotiniel commented on src/App.vue
> +        return { color: "black" };
@noejunior792 Try to experiment with different shades of yellows.

2024-08-08 15:31 UTC, noejunior792 commented on src/App.vue
> +        return { color: "black" };
![Captura de ecrã 2024-08-08 163017](https://github.com/user-attachments/assets/c165cd2a-4ec9-4a07-83b6-ed321695104b)
Like this?

2024-08-08 16:09 UTC, euotiniel commented on src/App.vue
> +        return { color: "black" };
What did you think?

2024-08-08 16:12 UTC, noejunior792 commented on src/App.vue
> +        return { color: "black" };
Better than the previous one, can I make a pull request with the change?

2024-08-08 16:25 UTC, euotiniel commented on src/App.vue
> +        return { color: "black" };
Undoubtedly.

2024-08-08 16:46 UTC, closed without merging